# Generated by Django 4.2.8 on 2023-12-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0006_alter_about_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
