# Generated by Django 4.2.8 on 2023-12-19 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0007_orderproduct_user_id_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='user_id',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.user'),
        ),
    ]
