# Generated by Django 4.2.8 on 2023-12-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0008_remove_orderproduct_user_id_orderproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=None, editable=False, unique=True),
        ),
    ]
