# Generated by Django 4.2.8 on 2023-12-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0011_alter_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_type',
            new_name='product_id',
        ),
    ]
