# Generated by Django 4.2.8 on 2023-12-20 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0012_rename_payment_type_order_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
    ]
