# Generated by Django 4.2.8 on 2023-12-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0013_remove_orderproduct_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='heading_en',
        ),
        migrations.RemoveField(
            model_name='new',
            name='heading_ru',
        ),
        migrations.RemoveField(
            model_name='new',
            name='heading_uz',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
