# Generated by Django 4.2.8 on 2023-12-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0014_remove_new_heading_en_remove_new_heading_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
