# Generated by Django 4.2.8 on 2023-12-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0015_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(unique=True),
        ),
    ]
