# Generated by Django 4.2.8 on 2023-12-23 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0017_user_shop_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=150)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.shop_name')),
            ],
            options={
                'verbose_name': 'Shop name',
                'verbose_name_plural': 'Shop name',
            },
        ),
    ]
