# Generated by Django 4.2.8 on 2024-01-12 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bot_app', '0020_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='user_id',
            new_name='chat_id',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='name',
        ),
        migrations.AddField(
            model_name='admin',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2024, 1, 12, 21, 28, 43, 949560, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='admin_groups', related_query_name='admin_group', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='admin',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='admin',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default=datetime.datetime(2024, 1, 12, 21, 28, 49, 845881, tzinfo=datetime.timezone.utc), max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='admin_permissions', related_query_name='admin_permission', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
